"""add download_count column

Revision ID: 72f08e8a64be
Revises: e20e4eba0e11
Create Date: 2021-03-29 19:57:12.895063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f08e8a64be'
down_revision = 'e20e4eba0e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('download_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'download_count')
    # ### end Alembic commands ###
